name: Add 1 item to the blockchain
on:
    workflow_dispatch:
    schedule:
        # Run at 06:00, 12:00, 15:00 every day
        # Copy of existing schedule from macserver
        - cron: "0 13 * * *"
jobs:
    scrape:
        runs-on: ubuntu-latest
        steps:
            - name: Set default branch name to `main`
              run: git config --global init.defaultBranch main
            - name: Check out main repo
              uses: actions/checkout@v4
              with:
                  token: ${{ secrets.GH_TOKEN }}
            - name: Set Git config
              run: |
                  git config --global user.email "github@ari-s.com"
                  git config --global user.name "Ari Stassinopoulos (Bot)"
            - name: Build and run
              run: |
                  make -f Makefile innie
                  git add bin/*
                  git commit -m "Add another block to the blockchain"
                  git push origin main
